trigger:
- master

pool:
 name: 'local'
 demands:
      - Agent.Name -equals amazonliux
stages:
  - stage: Build
    jobs:
    - job: Build_Stage
      steps:
       - script:
           echo "Hello From Build Stage"
  - stage: Test
    jobs:
     - job: Test_Stage
       steps:
       - script: 
          echo "Hello From Test stage"
  - stage: Deploy
    jobs:
    - job: DeployStage
      steps:
      - script: 
         echo "Hello from Deploy Stage"
  - stage: DockerBuild
    jobs:
     - job: Build_Stage
       steps:
         - script:  
              docker build -t nginx:v1 .  
              docker tag nginx:v1  nginx:latest 861923434973.dkr.ecr.ap-south-1.amazonaws.com/nginx:latest                   
  - stage: ECRPush
    jobs:
      - job: 
        steps:
        - task: ECRPushImage@1
          inputs:
            regionName: 'ap-south-1'
            imageSource: 'imagename'
            sourceImageName: 'nginx'
            repositoryName: 'nginx:latest 861923434973.dkr.ecr.ap-south-1.amazonaws.com'
            removeDockerImage: true