trigger:
 - master
pool:
 name: 'local'
stages:
  - stage:
    jobs:
    - job: Build_Stage
      steps:
       - script:
           echo "Hello From Build Stage"
  - stage:
    jobs:
     - job: Test_Stage
       steps:
       - script: 
          echo "Hello From Test stage"          

