trigger:
- master

pool:
 name: 'local'
 demands:
      - Agent.Name -equals amazonliux
stages:
  - stage: Build
    jobs:
    - job: Build_Stage
      steps:
       - script:
           echo "Hello From Build Stage"
  - stage: Test
    jobs:
     - job: Test_Stage
       steps:
       - script: 
          echo "Hello From Test stage"
  - stage: DeployToStage
    dependsOn: Test
    jobs:
    - job: DeployToStage      
      steps:
      - script: 
         echo "Hello from Deploy Stage"
  - stage: DeployToProd
    dependsOn: Test
    jobs:
     - job: DeployToProd
       steps:
         - script: echo "Deploying to Prod"            