trigger:
- master

pool:
 name: 'local'
 demands:
      - Agent.Name -equals amazonliux
stages:
  - stage: Build
    jobs:
    - job: Build_Stage
      steps:
       - script:
           echo "Hello From Build Stage"
  - stage: Test
    jobs:
     - job: Test_Stage
       steps:
       - script: 
          echo "Hello From Test stage"
  - stage: DeployToQA
    dependsOn: Test
    jobs:
    - job: DeployToQA     
      steps:
      - script: 
         echo "Hello from Deploy QA"
  - stage: DeployToStage
    dependsOn: Test
    jobs:
     - job: DeployToProd
       steps:
         - script: echo "Deploying to Stage" 
  - stage: DeployToProd
    dependsOn:
    - DeployToQA
    - DeployToStage
    jobs:
    - job:
      steps:
        - script: echo "Deploying to Prod"                     