trigger:
 - master
pool:
 name: 'local'
 demands:
      - Agent.Name -equals amazonlinux
stages:
  - stage: Build
    jobs:
    - job: Build_Stage
      steps:
       - script:
           echo "Hello From Build Stage"
  - stage: Test
    jobs:
     - job: Test_Stage
       steps:
       - script: 
          echo "Hello From Test stage"
  - stage: Deploy
    jobs:
    - job: DeployStage
      steps:
      - script: 
         echo "Hello from Deploy Stage"
  - stage: DockerBuild
    jobs:
     - job: Build_Stage
       steps:
         - script:  
              docker build -t nginx:v1 .                      

